package web

import (
	"embed"
	"io/fs"
)

// embedded contains the production frontend generated by Vite. The all:
// prefix also includes the placeholder used by source-only development builds.
//
//go:embed all:dist
var embedded embed.FS

// Dist returns the embedded frontend with dist as its filesystem root.
func Dist() fs.FS {
	dist, err := fs.Sub(embedded, "dist")
	if err != nil {
		panic(err)
	}
	return dist
}
